name: fGameMode
version: ${project.version}
main: com.flaplings.gamemode.GameModePlugin
authors:
  - Voigon
  - Daniel Naaman
api-version: 1.13
commands:
  gamemode:
    aliases:
      - gm
    description: Set gamemode
  gmc:
    description: Set  gamemode to creative
  gms:
    description: Set gamemode to survival
  gma:
    description: Set gamemode to adventure
  gmsp:
    description: Set gamemode to spectator
permissions:
  fgamemode.reload:
    default: op
    description: Reload the configuration
  fgamemode.announce:
    default: op
    description: Announce gammemode change to, if enabled in config
  fgamemode.others:
    default: op
    description: Set other player's gamemode
  fgamemode.creative:
    default: op
    description: Set gamemode to creative
  fgamemode.survival:
    default: op
    description: Set gamemode to survival
  fgamemode.adventure:
    default: op
    description: Set gamemode to adventure
  fgamemode.spectator:
    default: op
    description: Set gamemode to spectator