name: fGameMode
version: ${project.version}
main: com.flaplings.gamemode.GameModePlugin
authors: [ Voigon ]
api-version: 1.13
commands:
  gamemode:
    permission: fgamemode
    aliases:
      - gm
  gmc:
    permission: fgamemode.creative
  gms:
    permission: fgamemode.survival
  gma:
    permission: fgamemode.adventure
  gmsp:
    permission: fgamemode.spectator
permissions:
  fgamemode.reload:
    default: false
    description: Reload the configuration
  fgamemode.announce:
    default: op
    description: Announce gammemode change to, if enabled in config